version: '3'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application
    volumes:
      - ./backend:/app
    expose:
      - "8000"

  aiogram:
    build:
      context: ./backend
      dockerfile: Dockerfile.aiogram
    volumes:
      - ./backend:/app
    expose:
      - "8443"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
      - frontend
